version: '3.8'

services:
  nxzap:
    image: 'op3000/nxzap:1.1.4'
    privileged: true
    container_name: nxzap
    restart: unless-stopped
    ports:
      - '8082:8080'
    environment:
      URL_WEBHOOK_MENSAGENS: 'https://nxbr-demonstrativo-api.nexum.com.br/api/v1/webhooks/atendimento/mensagens'
      DB_NAME: 'DEMO_NXZAP_PRD'
      DB_URL: 'mongodb://nxzap:Av3M6ZZ3cSKRa5zGE7@mongodb:27017/?retryWrites=true&w=majority'
      TOKEN_META: ${TOKEN_META}
      URL_META: ${URL_META}
      URL_META_MEDIA: ${URL_META_MEDIA}
      TOKEN_TELEGRAM: ${TOKEN_TELEGRAM}
    networks:
      - app_network
    depends_on:
      - mongodb

  nxzap-coopacredi:
    image: 'op3000/nxzap:1.0.6'
    privileged: true
    container_name: nxzap-coopacredi
    restart: unless-stopped
    ports:
      - '8085:8080'
    environment:
      URL_WEBHOOK_MENSAGENS: 'https://api-coopacredi.nexum.com.br/api/v1/webhooks/atendimento/mensagens'
      DB_NAME: 'COOPACREDI_NXZAP_PRD'
      DB_URL: 'mongodb://nxzap:Av3M6ZZ3cSKRa5zGE7@mongodb:27017/?retryWrites=true&w=majority'
      TOKEN_META: ${TOKEN_META}
      URL_META: ${URL_META}
      URL_META_MEDIA: ${URL_META_MEDIA}
      TOKEN_TELEGRAM: ${TOKEN_TELEGRAM}
    networks:
      - app_network
    depends_on:
      - mongodb

  nxzap-coonecta:
    image: 'op3000/nxzap:1.0.9'
    privileged: true
    container_name: nxzap-coonecta
    restart: unless-stopped
    ports:
      - '8084:8080'
    environment:
      URL_WEBHOOK_MENSAGENS: 'https://api-coonecta.nexum.com.br/api/v1/webhooks/atendimento/mensagens'
      DB_NAME: 'CREDISUL_NXZAP_PRD'
      DB_URL: 'mongodb://nxzap:Av3M6ZZ3cSKRa5zGE7@mongodb:27017/?retryWrites=true&w=majority'
      TOKEN_META: ${TOKEN_META}
      URL_META: ${URL_META}
      URL_META_MEDIA: ${URL_META_MEDIA}
      TOKEN_TELEGRAM: ${TOKEN_TELEGRAM}
    networks:
      - app_network
    depends_on:
      - mongodb

  nxzap-credisul:
    image: 'op3000/nxzap:1.1.0'
    privileged: true
    container_name: nxzap-credisul
    restart: unless-stopped
    ports:
      - '8095:8080'
    environment:
      URL_WEBHOOK_MENSAGENS: 'https://api-credisul.nexum.com.br/api/v1/webhooks/atendimento/mensagens'
      DB_NAME: 'CREDISUL_NXZAP_PRD'
      DB_URL: ''mongodb://nxzap:Av3M6ZZ3cSKRa5zGE7@mongodb:27017'/?retryWrites=true&w=majority'
      TOKEN_META: ${TOKEN_META}
      URL_META: ${URL_META}
      URL_META_MEDIA: ${URL_META_MEDIA}
      TOKEN_TELEGRAM: ${TOKEN_TELEGRAM}
    networks:
      - app_network
    depends_on:
      - mongodb

  # nxzap-desenvolvimento:
  #   image: 'op3000/nxzap:1.1.2'
  #   privileged: true
  #   container_name: nxzap-desenvolvimento
  #   restart: unless-stopped
  #   ports:
  #     - "8096:8080"
  #   environment:
  #     URL_WEBHOOK_MENSAGENS: ''
  #     DB_NAME: 'CREDISUL_NXZAP_PRD'
  #     DB_URL: 'mongodb://nxzap:Av3M6ZZ3cSKRa5zGE7@mongodb:27017/?retryWrites=true&w=majority'
  #     TOKEN_META: ${TOKEN_META}
  #     URL_META: ${URL_META}
  #     URL_META_MEDIA: ${URL_META_MEDIA}
  #     TOKEN_TELEGRAM: ${TOKEN_TELEGRAM}
  #   networks:
  #     - app_network
  #   depends_on:
  #     - mongodb

  # nxzap-coopmetro:
  #   image: 'op3000/nxzap:1.1.2'
  #   privileged: true
  #   container_name: nxzap-coopmetro
  #   restart: unless-stopped
  #   ports:
  #     - "8097:8080"
  #   environment:
  #     URL_WEBHOOK_MENSAGENS: ''
  #     DB_NAME: 'NxZapCoopMetro'
  #     DB_URL: 'mongodb://nxzap:Av3M6ZZ3cSKRa5zGE7@mongodb:27017/?retryWrites=true&w=majority'
  #     TOKEN_META: ${TOKEN_META}
  #     URL_META: ${URL_META}
  #     URL_META_MEDIA: ${URL_META_MEDIA}
  #     TOKEN_TELEGRAM: ${TOKEN_TELEGRAM}
  #   networks:
  #     - app_network
  #   depends_on:
  #     - mongodb

  nx-encurtador:
    image: 'op3000/nxencurtador:1.0.4'
    privileged: true
    container_name: nxencurtador
    restart: unless-stopped
    ports:
      - '8086:8093'
    environment:
      DB_NAME: 'NEXUM_NXENCURTADOR_PRD'
      DB_URL: 'mongodb://nxzap:Av3M6ZZ3cSKRa5zGE7@mongodb:27017/?retryWrites=true&w=majority'
      URL: 'https://encurtador.nexum.com.br'
    networks:
      - app_network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - '8083:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: nxzap
      MONGO_INITDB_ROOT_PASSWORD: Av3M6ZZ3cSKRa5zGE7
      PUID: 1000
      PGID: 1000
    logging:
      options:
        max-size: 1g
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

volumes:
  mongodb_data:
    driver: local

networks:
  app_network:
    driver: bridge
